version: "3.4"

services:
  bot:
    build: .
    depends_on:
      - redis
    volumes:
      - ./.data/config.yml:/data/config.yml:delegated
    restart: always
    ports:
      - "8443:8443"
  redis:
    image: "redis:alpine"
    entrypoint: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./.data/redis:/data:delegated
    restart: always