version: "3.4"

services:
  bot:
    build: .
    depends_on:
      - redis
    volumes:
      - /etc/letsencrypt/live/:/data/letsencrypt:delegated
    restart: always
  redis:
    image: "redis:alpine"
    entrypoint: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./.data/redis:/data:delegated
    restart: always